apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: front-end
build:
  artifacts:
  - image: kchua405/sock-shop-frontend-skaffold
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/complete-demo-kenzo.yml
