apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: front-end
build:
  artifacts:
  - image: localhost:5000/nrsg/sock-shop-frontend-skaffold
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/deployment-svc-frontend.yml
